cd node_modules\nightwatch
node nightwatch.js -t EHRadmin/superadmin.js -r ./globals/superadmin/superadmin.js
node nightwatch.js -t EHRuser/createpatient.js -r ./globals/patient/createpatient.js
node nightwatch.js -t EHRadmin/createappointmentpatient.js -r ./globals/admin/createpatientappointment.js
node nightwatch.js -t EHRuser/passwordandusername.js -r ./globals/patient/passwordandusername.js
node nightwatch.js -t EHRuser/profile.js -r ./globals/patient/profile.js
node nightwatch.js -t EHRuser/appointment.js -r ./globals/patient/appointment.js
node nightwatch.js -t EHRuser/cpi.js -r ./globals/patient/cpi.js
node nightwatch.js -t EHRuser/consenttotreat.js -r ./globals/patient/consenttotreat.js
node nightwatch.js -t EHRuser/hippanotice.js -r ./globals/patient/hippanotice.js
node nightwatch.js -t EHRuser/assingmentattorney.js -r ./globals/patient/assignmentattorney.js
node nightwatch.js -t EHRuser/minor.js -r ./globals/patient/minor.js
node nightwatch.js -t EHRuser/auto.js -r ./globals/patient/auto.js
node nightwatch.js -t EHRuser/screening.js -r ./globals/patient/screening.js
node nightwatch.js -t EHRuser/healthinformation.js -r ./globals/patient/healthinfo.js
node nightwatch.js -t EHRuser/headache.js -r ./globals/patient/headache.js
node nightwatch.js -t EHRuser/neck.js -r ./globals/patient/neck.js
node nightwatch.js -t EHRuser/shoulderpain.js -r ./globals/patient/shoulderpain.js
node nightwatch.js -t EHRuser/midbackpain.js -r ./globals/patient/midbackpain.js
node nightwatch.js -t EHRuser/wristandhandpain.js -r ./globals/patient/wristandhandpain.js
node nightwatch.js -t EHRuser/lowbackpain.js -r ./globals/patient/lowbackpain.js
node nightwatch.js -t EHRuser/hippain.js -r ./globals/patient/hippain.js
node nightwatch.js -t EHRuser/kneepain.js -r ./globals/patient/kneepain.js
node nightwatch.js -t EHRuser/footandankle.js -r ./globals/patient/footandankle.js
node nightwatch.js -t EHRuser/addexamform.js -r ./globals/patient/addexam.js
node nightwatch.js -t EHRadmin/viewdoctor.js -r ./globals/admin/viewdoctor.js
node nightwatch.js -t EHRdoctor/profile.js -r ./globals/doctor/profile.js
node nightwatch.js -t EHRdoctor/examform1.js -r ./globals/doctor/exam1.js
node nightwatch.js -t EHRdoctor/examform2.js -r ./globals/doctor/exam2.js
node nightwatch.js -t EHRdoctor/examform3.js -r ./globals/doctor/exam3.js
node nightwatch.js -t EHRdoctor/examform4.js -r ./globals/doctor/exam4.js
node nightwatch.js -t EHRdoctor/examform5.js -r ./globals/doctor/exam5.js
node nightwatch.js -t EHRdoctor/examform6.js -r ./globals/doctor/exam6.js
node nightwatch.js -t EHRdoctor/examform7.js -r ./globals/doctor/exam7.js
node nightwatch.js -t EHRdoctor/examform8.js -r ./globals/doctor/exam8.js
node nightwatch.js -t EHRdoctor/radiologicalreport.js -r ./globals/doctor/radio.js
node nightwatch.js -t EHRdoctor/soapnotes.js -r ./globals/doctor/soap.js
node nightwatch.js -t EHRdoctor/ankleandfootexam.js -r ./globals/doctor/ankleandfootexam.js
node nightwatch.js -t EHRdoctor/cervicalexam.js -r ./globals/doctor/cervicalexam.js
node nightwatch.js -t EHRdoctor/elbowexam.js -r ./globals/doctor/elbowexam.js
node nightwatch.js -t EHRdoctor/hipexam.js -r ./globals/doctor/hipexam.js
node nightwatch.js -t EHRdoctor/lumbopelvicexam.js -r ./globals/doctor/lumbopelvicexam.js
node nightwatch.js -t EHRdoctor/shoulderexam.js -r ./globals/doctor/shoulderexam.js
node nightwatch.js -t EHRdoctor/thoracicexam.js -r ./globals/doctor/thoracicexam.js
node nightwatch.js -t EHRdoctor/wristandhandexam.js -r ./globals/doctor/wristandhandexam.js
node nightwatch.js -t EHRadmin/healthinsuranceverification.js -r ./globals/admin/healthinsuranceverification.js
node nightwatch.js -t EHRadmin/xrayrelease.js -r ./globals/admin/xrayrelease.js
node nightwatch.js -t EHRadmin/workschoolexcusedslip.js -r ./globals/admin/workschoolexcusedslip.js
node nightwatch.js -t EHRadmin/hardship.js -r ./globals/admin/hardship.js


node nightwatch.js -t EHRadmin/accountreceivable.js -r ./globals/admin/accountreceivable.js
node nightwatch.js -t EHRadmin/billing.js -r ./globals/admin/billing.js
node nightwatch.js -t EHRadmin/HICFA.js -r ./globals/admin/HICFA.js
node nightwatch.js -t EHRadmin/icdcodes.js -r ./globals/admin/ICD.js
node nightwatch.js -t EHRadmin/cptcodes.js -r ./globals/admin/CPT.js
node nightwatch.js -t EHRadmin/feeschedule.js -r ./globals/admin/fees.js
node nightwatch.js -t EHRadmin/taxanddiscount.js -r ./globals/admin/taxanddiscount.js
node nightwatch.js -t EHRadmin/clinicprofile.js -r ./globals/admin/clinicprofile.js
node nightwatch.js -t EHRadmin/requestform.js -r ./globals/admin/requestform.js